import {chromium} from 'playwright';
import {readFile,writeFile} from 'node:fs/promises';
const base='artifacts/lead-live-authorized-20261006';
const run=JSON.parse(await readFile(base+'/quantity-check/RUN.json','utf8'));
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/runs',r=>r.fulfill({contentType:'application/json',body:JSON.stringify([run])}));
await page.goto('http://127.0.0.1:14320');
await page.getByRole('button',{name:'증거 & 검토',exact:true}).click();
await page.getByText('입력값을 ‘2’로 변경',{exact:true}).waitFor();
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:base+'/QUANTITY_UI.png',fullPage:true});
await page.goto('http://127.0.0.1:14320/artifacts/lead-live-authorized-20261006/REVIEW.html');
await page.waitForFunction(()=>Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0));
await page.locator('section').filter({has:page.getByRole('heading',{name:'C · 뒤틀림',exact:true})}).screenshot({path:base+'/REFERENCE_C_REVIEW.png'});
await page.locator('section').filter({has:page.getByRole('heading',{name:'D · 컴포넌트 겹침',exact:true})}).screenshot({path:base+'/REFERENCE_D_REVIEW.png'});
await writeFile(base+'/UI_REVIEW.json',JSON.stringify({realRun:run.id,servedRecord:'GET /api/runs replay only; no model call',loadedImages:await page.locator('img').count(),pageErrors:errors},null,2));
await browser.close();
