from pathlib import Path
import json,html
b=Path('OUTBOX/VISION_AGENT_CONCEPT_2026_10_06_V1')
sources=json.loads((b/'SOURCES.json').read_text())['sources']
engine=(b/'CONCEPT_ENGINE.js').read_text()
content='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vision Agent — 화면에서 이해하고 행동하기</title><style>
:root{color-scheme:dark;--bg:#060c17;--ink:#e8f2ff;--muted:#98adc4;--mint:#52e0c7}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:system-ui,sans-serif;line-height:1.6}main{max-width:1200px;margin:auto;padding:44px 28px}small,.eyebrow{color:var(--mint);letter-spacing:.08em}h1{font-size:clamp(32px,5vw,62px);line-height:1.2;max-width:900px;margin:16px 0 24px}h2{font-size:25px}.lead{max-width:880px;font-size:21px;color:#c8daed}.tag{display:inline-block;border:1px solid #264559;border-radius:99px;padding:6px 14px;font-size:14px;color:var(--muted)}.stage{border:1px solid #203446;border-radius:20px;overflow:hidden;margin-top:32px;background:#0f1a2b}canvas{width:100%;height:auto;display:block;aspect-ratio:16/9}.controls{padding:20px;display:grid;gap:18px}.row{display:flex;flex-wrap:wrap;align-items:center;gap:14px}button,select{background:#15283b;border:1px solid #33526b;color:var(--ink);font:inherit;padding:10px 16px;border-radius:9px}button{cursor:pointer}button:hover{border-color:var(--mint)}button:focus-visible,select:focus-visible,input:focus-visible,a:focus-visible{outline:3px solid var(--mint);outline-offset:4px}input[type=range]{accent-color:var(--mint);width:100%;min-height:26px}label{display:block;color:#b7cce1}.range{flex:1;min-width:180px}#clock{font-variant-numeric:tabular-nums}#summary{color:#c8daed;min-height:3em}#detail{color:var(--mint)}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin:32px 0}.card{padding:24px;background:#0f1a2b;border:1px solid #203446;border-radius:16px}.card p{color:#b6cce0}.card h3{margin-top:0}a{color:var(--mint)}.note{border-left:3px solid #ffb557;padding:12px 22px;color:#d1dfed}.sources{font-size:15px;color:var(--muted)}footer{margin-top:42px;color:var(--muted)}@media(max-width:650px){main{padding:26px 16px}.cards{grid-template-columns:1fr}.lead{font-size:18px}.controls{padding:16px}select{max-width:100%;width:100%}}
</style></head><body><main><div class="eyebrow">VISION AGENT · AN INTERACTIVE EXPLAINER</div><h1>화면의 의미를 읽고,<br>다음 행동을 선택합니다.</h1><p class="lead">Vision 기반 Agent의 차별점은 화면을 행동의 입력으로 삼는 데 있습니다. 현재 화면과 목표를 연결하고, 행동 뒤의 새 화면을 다시 관찰합니다.</p><span class="tag">일반 개념 자료 · 프로젝트 실험 미포함</span> <span class="tag">개념 애니메이션 · 실제 모델 실행 아님</span>
<section class="stage" aria-label="Vision Agent 개념 애니메이션"><canvas width="1280" height="720" role="img" aria-label="장면별 개념 애니메이션. 아래 설명과 장면 선택으로 내용을 확인할 수 있습니다."></canvas><div class="controls"><div class="row"><button id="play" type="button">재생</button><button id="reset" type="button">처음으로</button><span id="clock">0:00 / 2:48</span><label for="chapter">장면</label><select id="chapter"></select></div><label for="time">시간 이동<input id="time" type="range" min="0" max="167.99" step="0.01" value="0"></label><label for="variation">변화 직접 조절 — 03 위치 이동 · 07 선택 상태 · 08 대상 간격<input id="variation" type="range" min="0" max="100" step="1" value="50"></label><div><strong id="detail"></strong><p id="summary"></p></div></div></section>
<section class="cards" aria-label="차별점 네 가지"><article class="card"><h3>01 · 시각적 의미로 대상 찾기</h3><p>텍스트뿐 아니라 아이콘의 모양, 위치, 주변 맥락을 함께 이용합니다. 구조 정보가 적은 Canvas나 이미지 중심 UI에도 적용할 수 있습니다.</p><p>인식과 위치 선택이 정확해야 합니다. 비슷한 아이콘이나 작은 글자에서는 틀릴 수 있습니다.</p></article><article class="card"><h3>02 · 새 화면으로 다음 선택 바꾸기</h3><p>처음 계획만 고정하는 대신, 행동 결과를 관찰한 뒤 계속 진행할지·대기할지·경로를 바꿀지 선택할 수 있습니다.</p><p>대화상자가 나타나는 장면은 이 관계를 설명하는 예시이며 실제 Agent 실행이 아닙니다.</p></article><article class="card"><h3>03 · 보이는 결과를 자연어 요구와 대조</h3><p>선택 상태·진행 상태·화면 전후 변화처럼 사용자에게 보이는 결과를 질문합니다. 기준 이미지가 없어도 현재 화면을 자연어 기준과 대조할 수 있습니다.</p><p>기준이 모호하면 판정도 모호해집니다. 결과에는 전후 화면과 이유를 남겨야 합니다.</p></article><article class="card"><h3>04 · 화면을 공통 관찰 입력으로 사용</h3><p>Web·데스크톱·모바일은 내부 구조가 달라도 화면을 공통 입력으로 사용할 수 있습니다. 실행에는 환경별 클릭·터치·키 입력 도구와 권한이 필요합니다.</p><p>동일 정확도나 모든 플랫폼의 자동 지원을 뜻하지는 않습니다.</p></article></section>
<section class="note"><h2>기존 자동화와 함께 봐야 합니다.</h2><p>DOM/API 기반 검사는 명확한 값·계약·반복 검증에 유용합니다. role·label locator는 위치가 바뀌어도 대상을 찾을 수 있습니다. Playwright는 기준 스크린샷 비교도 제공합니다. 따라서 시각 검증 자체를 Vision만의 독점 기능으로 설명하지 않습니다.</p><p>Vision은 구조 정보에 덜 의존하는 화면 해석과 자연어 검토를 더할 수 있습니다. 오판·지연·모델 비용과 민감한 화면의 전송 여부를 고려하고, 중요한 업무는 실행 범위와 검토 기준을 정해야 합니다.</p></section>
<section class="sources"><h2>출처와 해석 범위</h2><p>2026-10-06 공식 문서와 연구를 확인했습니다. 화면·아이콘·연결선·판정 흐름은 직접 만든 설명용 도해입니다. 성능 수치, 고객 반응, 프로젝트 테스트 결과는 포함하지 않습니다.</p><ul>'''
content+=''.join(f'<li><a href="{html.escape(s["url"])}">{html.escape(s["title"])}</a> — {html.escape(s["supports"])}</li>' for s in sources)
content+='''</ul><p>애니메이션의 흐름과 네 가지 분류는 위 자료를 종합한 설명 구조입니다. 특정 모델이 모든 장면에 성공한다는 실증 결과가 아닙니다.</p></section><footer>LUMEN · Vision Agent Concept V1<br>독립 단일 HTML · 외부 라이브러리/폰트/모델 호출 없음 · 처음에는 정지 상태</footer></main><script>'''+engine+'</script></body></html>'
(b/'VISION_AGENT_CONCEPT.html').write_text(content)
print('Standalone HTML created',len(content.encode()),'bytes')
