import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(require.resolve('playwright',{paths:[resolve('REPOS/vision-test-maker/apps/platform')]}));
const base=resolve('OUTBOX/VISION_AGENT_CONCEPT_2026_10_06_V1');
await mkdir(base+'/HTML_QA',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});
await page.goto(pathToFileURL(base+'/VISION_AGENT_CONCEPT.html').href);
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:base+'/HTML_QA/DESKTOP.png'});
const sceneScreens=[];
for(let n=0;n<12;n++){
 await page.evaluate(n=>window.concept.seek(n*14+7),n);
 await page.locator('canvas').screenshot({path:`${base}/HTML_QA/SCENE_${String(n+1).padStart(2,'0')}.png`});
 sceneScreens.push(await page.locator('#detail').textContent());
}
await page.selectOption('#chapter','2');
await page.locator('#variation').fill('0');
await page.locator('#variation').dispatchEvent('input');
const left=await page.locator('canvas').screenshot();
await page.locator('#variation').fill('100');
await page.locator('#variation').dispatchEvent('input');
const right=await page.locator('canvas').screenshot();
if(left.equals(right))throw Error('Position variation did not change rendered frame');
await page.locator('#reset').click();
await page.locator('#play').click();
await page.waitForTimeout(1300);
const played=await page.evaluate(()=>window.concept.state());
await page.locator('#play').click();
if(!(played.time>0.8&&played.playing))throw Error('Playback did not advance');
const paused=await page.evaluate(()=>window.concept.state());
await page.waitForTimeout(350);
const still=await page.evaluate(()=>window.concept.state());
if(still.time!==paused.time||still.playing)throw Error('Pause did not hold');
await page.locator('#time').fill('90');await page.locator('#time').dispatchEvent('input');
const sought=await page.evaluate(()=>window.concept.state());
if(sought.time!==90)throw Error('Scrub failed');
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>window.concept.seek(35));await page.evaluate(()=>scrollTo(0,0));
await page.screenshot({path:base+'/HTML_QA/MOBILE_TOP.png'});
await page.locator('#variation').scrollIntoViewIfNeeded();
await page.screenshot({path:base+'/HTML_QA/MOBILE_CONTROLS.png'});
const mobile=await page.evaluate(()=>({width:innerWidth,body:document.documentElement.scrollWidth,chapterCount:document.querySelector('#chapter').options.length}));
if(mobile.body>mobile.width||mobile.chapterCount!==12||errors.length||external.length)throw Error(JSON.stringify({mobile,errors,external}));
await writeFile(base+'/HTML_QA/REPORT.json',JSON.stringify({desktop:[1440,1100],mobile,sceneScreens,position_variation_changes_frame:true,play_advances:true,pause_holds:true,scrub:true,pageErrors:errors,externalRequests:external,mode:'local standalone file; no model calls'},null,2));
await browser.close();console.log('HTML QA passed: 12 chapters, interaction, desktop/mobile, zero errors/external requests');
