import { expect } from "@playwright/test";
import type { Page } from "playwright";
export async function sampleBaseline(page: Page, beforeSubmit?: () => Promise<void>, url = "http://127.0.0.1:4311/order") {
 await page.goto(url);
 await expect(page.locator("html")).toHaveAttribute("lang","ko");
 await page.waitForLoadState("networkidle");
 await expect(page.getByRole("button",{name:"주문 확정하기"})).toBeDisabled();
 await page.getByLabel("받는 분").fill("김민수");
 await page.getByLabel("이메일 주소").fill("invalid");
 await expect(page.getByText("올바른 이메일 주소를 입력해주세요.")).toBeVisible();
 await expect(page.getByRole("button",{name:"주문 확정하기"})).toBeDisabled();
 await page.getByLabel("이메일 주소").fill("alex@example.test");
 await page.getByLabel("수량",{exact:true}).fill("0");
 await expect(page.getByText("수량은 1~5개의 정수로 입력해주세요.")).toBeVisible();
 await expect(page.getByRole("button",{name:"주문 확정하기"})).toBeDisabled();
 await page.getByRole("radio",{name:"케이블 클립",exact:true}).click();
 await page.getByLabel("수량",{exact:true}).fill("3");
 await expect(page.getByTestId("preview-total")).toHaveText("$24.00");
 await page.getByRole("radio",{name:"스튜디오 노트",exact:true}).click();
 await page.getByLabel("수량",{exact:true}).fill("2");
 await expect(page.getByTestId("preview-total")).toHaveText("$64.00");
 await page.getByRole("radio",{name:"빨간 머그",exact:true}).click();
 await expect(page.getByTestId("preview-total")).toHaveText("$24.00");
 await expect(page.getByRole("img",{name:"빨간 머그",exact:true})).toBeVisible();
 await expect(page.getByTestId("chart-first")).toHaveText("노트 · 80%");
 await expect(page.getByTestId("chart-second")).toHaveText("머그 · 20%");
 await expect(page.getByRole("img",{name:"인기 상품 비율: 노트 80%, 머그 20%"})).toBeVisible();
 await expect(page.getByRole("button",{name:"주문 확정하기"})).toBeEnabled();

 if(beforeSubmit)await beforeSubmit();
 const submitted=page.waitForResponse(r=>r.url().endsWith("/api/orders")&&r.request().method()==="POST");
 await page.getByRole("button",{name:"주문 확정하기"}).click();
 const response=await submitted;expect(response.status()).toBe(201);
 expect(await response.json()).toMatchObject({product:"mug",quantity:2,name:"김민수",email:"alex@example.test",unitCents:1200,totalCents:2400});
 await expect(page.getByRole("heading",{name:"주문이 완료되었습니다."})).toBeVisible();
 await expect(page.getByTestId("recipient")).toHaveText("김민수 · alex@example.test");
 await expect(page.getByTestId("item")).toHaveText("빨간 머그 × 2$24.00");
 await expect(page.getByTestId("order-total")).toHaveText("합계$24.00");
 await expect(page.getByTestId("receipt-item")).toHaveText("빨간 머그 × 2$24.00");
 await expect(page.getByTestId("receipt-total")).toHaveText("합계$24.00");
 await expect(page.getByRole("region",{name:"주문 영수증"})).toBeVisible();
 await expect(page.getByTestId("instructions")).toHaveText("영업일 기준 2일 안에 배송됩니다.수령 가능 시간은 48시간입니다.수령할 때 사진이 있는 신분증이 필요합니다.");
 await page.waitForTimeout(400);
}
