import { expect } from "@playwright/test";
import type { Page } from "playwright";
export async function sampleBaseline(page: Page, beforeSubmit?: () => Promise<void>) {
 await page.goto("http://127.0.0.1:4311/order");
 await expect(page.getByRole("button",{name:"Confirm order"})).toBeDisabled();
 await page.getByLabel("Recipient name").fill("Alex Morgan");
 await page.getByLabel("Email address").fill("invalid");
 await expect(page.getByRole("button",{name:"Confirm order"})).toBeDisabled();
 await page.getByLabel("Email address").fill("alex@example.test");
 await page.getByLabel("Quantity",{exact:true}).fill("0");
 await expect(page.getByRole("button",{name:"Confirm order"})).toBeDisabled();
 await page.getByRole("radio",{name:"Cable clips",exact:true}).click();
 await page.getByLabel("Quantity",{exact:true}).fill("3");
 await expect(page.getByTestId("preview-total")).toHaveText("$24.00");
 await page.getByRole("radio",{name:"Studio notebook",exact:true}).click();
 await page.getByLabel("Quantity",{exact:true}).fill("2");
 await expect(page.getByTestId("preview-total")).toHaveText("$64.00");
 await page.getByRole("radio",{name:"Red mug",exact:true}).click();
 await expect(page.getByTestId("preview-total")).toHaveText("$24.00");
 await expect(page.getByRole("img",{name:"Red mug",exact:true})).toBeVisible();
 await expect(page.getByTestId("chart-first")).toHaveText("Notebooks · 80%");
 await expect(page.getByTestId("chart-second")).toHaveText("Mugs · 20%");
 await expect(page.getByRole("img",{name:"Community favourites: notebooks 80%, mugs 20%"})).toBeVisible();
 await expect(page.getByRole("button",{name:"Confirm order"})).toBeEnabled();
 await page.evaluate(()=>document.fonts.ready);
 if(beforeSubmit)await beforeSubmit();
 const submitted=page.waitForResponse(r=>r.url().endsWith("/api/orders")&&r.request().method()==="POST");
 await page.getByRole("button",{name:"Confirm order"}).click();
 const response=await submitted;expect(response.status()).toBe(201);
 expect(await response.json()).toMatchObject({product:"mug",quantity:2,name:"Alex Morgan",email:"alex@example.test",unitCents:1200,totalCents:2400});
 await expect(page.getByRole("heading",{name:"Order confirmed"})).toBeVisible();
 await expect(page.getByTestId("recipient")).toHaveText("Alex Morgan · alex@example.test");
 await expect(page.getByTestId("item")).toHaveText("Red mug × 2$24.00");
 await expect(page.getByTestId("order-total")).toHaveText("Total$24.00");
 await expect(page.getByTestId("receipt-item")).toHaveText("Red mug × 2$24.00");
 await expect(page.getByTestId("receipt-total")).toHaveText("Total$24.00");
 await expect(page.getByRole("region",{name:"Order receipt"})).toBeVisible();
 await expect(page.getByTestId("instructions")).toHaveText("Delivery in 2 business days.Collection window: 48 hours.Photo ID is required at pickup.");
 await page.waitForTimeout(400);
}
